name: Build and User Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'

  Stage1:
    runs-on: ubuntu-latest
    needs: Pre-Dev-Steps
    steps:
      - name: 'Echo stage 1'
        run: echo 'Stage 1'

  Stage2:
    runs-on: ubuntu-latest
    needs: Stage1
    steps:
      - name: 'Echo stage 2'
        run: echo 'Stage 2'

  Stage3:
    runs-on: ubuntu-latest
    needs: Stage2
    steps:
      - name: 'Create user and await manual approval'
        id: create_user
        run: |
          # Logic to create user
          # You may need to replace this with actual commands to create a user

          # Assuming you have a variable to indicate manual approval, replace 'manual_approval' with the actual variable name
          if [[ $manual_approval == true ]]; then
            echo "::set-output name=approval_required::true"
          else
            echo "::set-output name=approval_required::false"
          fi
 Dev-Env:
    runs-on: ubuntu-latest
    needs: Stage3
    environment:
      name: manual_env
    steps:
      - name: 'Run some manual_env steps'
        shell: pwsh
        run: |
          Write-Host 'Done some manual_env deploy work'

  Stage4:
    runs-on: ubuntu-latest
    needs: Dev-Env
    if: ${{ needs.Stage3.outputs.create_user == 'false' }}
    steps:
      - name: 'Echo stage 4'
        run: echo 'Stage 4'

  Stage5:
    runs-on: ubuntu-latest
    needs: Dev-Env
    if: ${{ needs.Stage3.outputs.create_user == 'true' }}
    steps:
      - name: 'Echo stage 5'
        run: echo 'Stage 5'
