name: Build and Review Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Run some pre-dev steps
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'

  Review-Deployment:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Deploy for review
        shell: pwsh
        run: |
          Write-Host 'Deploying for review'
