name: Build and User Approval Workflow
on:
  push:
    branches:
      - main
jobs:
  Pre-Dev-Steps:
    runs-on: ubuntu-latest
    steps:
      - name: 'Run some predev steps'
        shell: pwsh
        run: |
          Write-Host 'Done some pre dev env deploy work'
  Dev-Env:
    runs-on: ubuntu-latest
    needs: Pre-Dev-Steps
    steps:
      - name: 'Run some manual steps'
        shell: pwsh
        run: |
          Write-Host 'Done some manual deploy work'
